// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(SlimBuddyDBContext))]
    [Migration("20240327113451_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Fruit",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5779)
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Drink",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5780)
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Snack",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5781)
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Dessert",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5781)
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Vegetable",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5782)
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Dairy",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5783)
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Fish and Seafood",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5783)
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Fast Food",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5784)
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Meat or Poultry",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5784)
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Others",
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5785)
                        });
                });

            modelBuilder.Entity("Models.Concrete.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<double>("Calorie")
                        .HasColumnType("float");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("MealID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("MealID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Calorie = 52.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5887),
                            Image = "\\Resources\\Apple.jpeg",
                            Name = "Apple",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 2,
                            Calorie = 47.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5891),
                            Image = "\\Resources\\Orange.jpg",
                            Name = "Orange",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 3,
                            Calorie = 131.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5892),
                            Image = "\\Resources\\Banana.jpg",
                            Name = "Banana",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 4,
                            Calorie = 46.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5893),
                            Image = "\\Resources\\Plum.jpeg",
                            Name = "Plum",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 5,
                            Calorie = 61.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5894),
                            Image = "\\Resources\\Kiwi.jpg",
                            Name = "Kiwi",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 6,
                            Calorie = 30.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5895),
                            Image = "\\Resources\\Watermelon.jpg",
                            Name = "Watermelon",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 7,
                            Calorie = 34.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5897),
                            Image = "\\Resources\\Melon.jpg",
                            Name = "Melon",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 8,
                            Calorie = 59.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5898),
                            Image = "\\Resources\\Peach.jpeg",
                            Name = "Peach",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 9,
                            Calorie = 60.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5899),
                            Image = "\\Resources\\Mango.jpg",
                            Name = "Mango",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 10,
                            Calorie = 50.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5900),
                            Image = "\\Resources\\Cherry.jpg",
                            Name = "Cherry",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 11,
                            Calorie = 0.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5901),
                            Image = "\\Resources\\Water.jpg",
                            Name = "Water",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 12,
                            Calorie = 113.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5902),
                            Image = "\\Resources\\Milkshake.jpg",
                            Name = "Milkshake",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 13,
                            Calorie = 37.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5903),
                            Image = "\\Resources\\Cola.jpg",
                            Name = "Cola",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 14,
                            Calorie = 48.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5904),
                            Image = "\\Resources\\Fanta.jpg",
                            Name = "Fanta",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 15,
                            Calorie = 89.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5905),
                            Image = "\\Resources\\Hotchocolate.jpg",
                            Name = "Hot Chocolate",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 16,
                            Calorie = 53.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5907),
                            Image = "\\Resources\\Soda.jpg",
                            Name = "Soda",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 17,
                            Calorie = 1.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5908),
                            Image = "\\Resources\\Coffee.jpg",
                            Name = "Coffee",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 18,
                            Calorie = 45.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5909),
                            Image = "\\Resources\\Orangejuice.jpg",
                            Name = "Orange Juice",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 19,
                            Calorie = 2.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5910),
                            Image = "\\Resources\\Tea.jpg",
                            Name = "Tea",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 20,
                            Calorie = 42.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5911),
                            Image = "\\Resources\\Lemonade.jpg",
                            Name = "Lemonade",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 21,
                            Calorie = 433.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5912),
                            Image = "\\Resources\\Wafer.jpg",
                            Name = "Wafer",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 22,
                            Calorie = 11.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5914),
                            Image = "\\Resources\\Almond.jpg",
                            Name = "Almond",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 23,
                            Calorie = 6.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5915),
                            Image = "\\Resources\\Peanut.png",
                            Name = "Peanut",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 24,
                            Calorie = 488.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5916),
                            Image = "\\Resources\\Snickers.jpeg",
                            Name = "Snickers",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 25,
                            Calorie = 375.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5917),
                            Image = "\\Resources\\Popcorn.jpeg",
                            Name = "Popcorn",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 26,
                            Calorie = 536.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5918),
                            Image = "\\Resources\\Chips.jpg",
                            Name = "Chips",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 27,
                            Calorie = 502.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5920),
                            Image = "\\Resources\\Cookies.jpg",
                            Name = "Cookies",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 28,
                            Calorie = 20.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5921),
                            Image = "\\Resources\\Crackers.jpg",
                            Name = "Crackers",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 29,
                            Calorie = 559.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5922),
                            Image = "\\Resources\\Sunflowerseed.jpg",
                            Name = "Sunflower Seed",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 30,
                            Calorie = 318.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5923),
                            Image = "\\Resources\\Marshmallow.jpg",
                            Name = "Marshmallow",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 31,
                            Calorie = 321.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5924),
                            Image = "\\Resources\\Cheesecake.jpg",
                            Name = "Cheesecake",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 32,
                            Calorie = 174.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5925),
                            Image = "\\Resources\\Baklava.jpg",
                            Name = "Baklava",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 33,
                            Calorie = 438.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5926),
                            Image = "\\Resources\\Doughnut.jpg",
                            Name = "Doughnut",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 34,
                            Calorie = 321.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5927),
                            Image = "\\Resources\\Cremebrulee.jpg",
                            Name = "Creme brulee",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 35,
                            Calorie = 49.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5928),
                            Image = "\\Resources\\Cookie.jpg",
                            Name = "Cookie",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 36,
                            Calorie = 466.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5929),
                            Image = "\\Resources\\Brownie.jpg",
                            Name = "Brownie",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 37,
                            Calorie = 250.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5930),
                            Image = "\\Resources\\Icecream.jpg",
                            Name = "Ice cream",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 38,
                            Calorie = 290.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5931),
                            Image = "\\Resources\\Tiramisu.jpg",
                            Name = "Tiramisu",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 39,
                            Calorie = 271.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5933),
                            Image = "\\Resources\\Pavlova.jpg",
                            Name = "Pavlova",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 40,
                            Calorie = 120.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5934),
                            Image = "\\Resources\\Pudding.jpg",
                            Name = "Pudding",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 41,
                            Calorie = 33.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5935),
                            Image = "\\Resources\\Brocoli.jpg",
                            Name = "Broccoli",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 42,
                            Calorie = 15.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5936),
                            Image = "\\Resources\\Cucumber.jpg",
                            Name = "Cucumber",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 43,
                            Calorie = 42.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5937),
                            Image = "\\Resources\\Celery.jpg",
                            Name = "Celery",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 44,
                            Calorie = 16.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5938),
                            Image = "\\Resources\\Courgette.jpg",
                            Name = "Courgette",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 45,
                            Calorie = 24.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5939),
                            Image = "\\Resources\\Eggplant.jpg",
                            Name = "Eggplant",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 46,
                            Calorie = 19.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5940),
                            Image = "\\Resources\\Tomatoes.jpg",
                            Name = "Tomatoes",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 47,
                            Calorie = 41.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5941),
                            Image = "\\Resources\\Carrot.jpg",
                            Name = "Carrot",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 48,
                            Calorie = 39.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5942),
                            Image = "\\Resources\\Pepper.jpg",
                            Name = "Pepper",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 49,
                            Calorie = 47.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5943),
                            Image = "\\Resources\\Artichoke.jpg",
                            Name = "Artichoke",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 50,
                            Calorie = 22.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5944),
                            Image = "\\Resources\\Mushroom.jpg",
                            Name = "Mushroom",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 51,
                            Calorie = 59.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5945),
                            Image = "\\Resources\\Yogurt.jpg",
                            Name = "Yogurt",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 52,
                            Calorie = 62.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5947),
                            Image = "\\Resources\\Tzatziki.jpg",
                            Name = "Tzatziki",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 53,
                            Calorie = 50.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5948),
                            Image = "\\Resources\\Ayran.jpg",
                            Name = "Ayran",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 54,
                            Calorie = 402.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5949),
                            Image = "\\Resources\\Cheddarcheese.jpg",
                            Name = "Cheddar cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 55,
                            Calorie = 98.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5951),
                            Image = "\\Resources\\Cottagecheese.jpg",
                            Name = "Cottage cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 56,
                            Calorie = 280.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5952),
                            Image = "\\Resources\\Mozzarellacheese.jpg",
                            Name = "Mozzarella cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 57,
                            Calorie = 42.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5953),
                            Image = "\\Resources\\Milk.jpg",
                            Name = "Milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 58,
                            Calorie = 68.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5954),
                            Image = "\\Resources\\Goatmilk.jpg",
                            Name = "Goat milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 59,
                            Calorie = 32.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5955),
                            Image = "\\Resources\\Almondmilk.jpg",
                            Name = "Almond milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 60,
                            Calorie = 54.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5956),
                            Image = "\\Resources\\Soymilk.jpg",
                            Name = "Soy milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 61,
                            Calorie = 164.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5957),
                            Image = "\\Resources\\Octopus.jpg",
                            Name = "Octopus",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 62,
                            Calorie = 124.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5964),
                            Image = "\\Resources\\Seabass.jpg",
                            Name = "Sea Bass",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 63,
                            Calorie = 264.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5965),
                            Image = "\\Resources\\Caviar.jpg",
                            Name = "Caviar",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 64,
                            Calorie = 89.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5966),
                            Image = "\\Resources\\Lobster.jpg",
                            Name = "Lobster",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 65,
                            Calorie = 175.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5967),
                            Image = "\\Resources\\Calamary.jpg",
                            Name = "Calamary",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 66,
                            Calorie = 159.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5968),
                            Image = "\\Resources\\Bluefish.jpg",
                            Name = "Blue Fish",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 67,
                            Calorie = 90.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5969),
                            Image = "\\Resources\\whiting.jpg",
                            Name = "Whiting",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 68,
                            Calorie = 206.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5970),
                            Image = "\\Resources\\Salmon.jpg",
                            Name = "Salmon",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 69,
                            Calorie = 150.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5972),
                            Image = "\\Resources\\Sushi.jpg",
                            Name = "Sushi",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 70,
                            Calorie = 262.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5973),
                            Image = "\\Resources\\Mackerel.jpg",
                            Name = "Mackerel",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 71,
                            Calorie = 295.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5975),
                            Image = "\\Resources\\Burger.jpg",
                            Name = "Burger",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 72,
                            Calorie = 266.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5976),
                            Image = "\\Resources\\Pizza.jpeg",
                            Name = "Pizza",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 73,
                            Calorie = 239.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5977),
                            Image = "\\Resources\\Doner.jpg",
                            Name = "Doner",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 74,
                            Calorie = 312.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5978),
                            Image = "\\Resources\\Frenchfries.jpg",
                            Name = "French fries",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 75,
                            Calorie = 164.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5979),
                            Image = "\\Resources\\Macandcheese.jpg",
                            Name = "Mac and cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 76,
                            Calorie = 118.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5980),
                            Image = "\\Resources\\Lahmacun.jpg",
                            Name = "Lahmacun",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 77,
                            Calorie = 390.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5981),
                            Image = "\\Resources\\Tantuni.jpg",
                            Name = "Tantuni",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 78,
                            Calorie = 284.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5982),
                            Image = "\\Resources\\Sandwich.jpg",
                            Name = "Sandwich",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 79,
                            Calorie = 411.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5983),
                            Image = "\\Resources\\Onionrings.jpeg",
                            Name = "Onion rings",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 80,
                            Calorie = 203.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5984),
                            Image = "\\Resources\\Chickenwing.jpg",
                            Name = "Chicken wing",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 81,
                            Calorie = 360.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5985),
                            Image = "\\Resources\\Adanakebab.jpg",
                            Name = "Adana Kebab",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 82,
                            Calorie = 235.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5987),
                            Image = "\\Resources\\Meatball.jpg",
                            Name = "Meatball",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 83,
                            Calorie = 336.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5988),
                            Image = "\\Resources\\Salami.jpg",
                            Name = "Salami",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 84,
                            Calorie = 300.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5989),
                            Image = "\\Resources\\Sausage.jpg",
                            Name = "Sausage",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 85,
                            Calorie = 186.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5990),
                            Image = "\\Resources\\Beefstew.jpg",
                            Name = "Beef Stew",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 86,
                            Calorie = 290.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5991),
                            Image = "\\Resources\\Chickenmarsal.jpg",
                            Name = "Chicken Marsal",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 87,
                            Calorie = 350.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5992),
                            Image = "\\Resources\\Chickentikkamasala.jpg",
                            Name = "Chicken Tikka Masala",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 88,
                            Calorie = 308.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5993),
                            Image = "\\Resources\\Chimichanga.jpg",
                            Name = "Chimichanga",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 89,
                            Calorie = 290.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5994),
                            Image = "\\Resources\\Fajita.jpg",
                            Name = "Fajita",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 90,
                            Calorie = 220.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5995),
                            Image = "\\Resources\\Steak.jpg",
                            Name = "Steak",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 91,
                            Calorie = 264.0,
                            CategoryID = 10,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5996),
                            Image = "\\Resources\\Bread.jpg",
                            Name = "Bread",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 92,
                            Calorie = 220.0,
                            CategoryID = 10,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5997),
                            Image = "\\Resources\\Egg.jpg",
                            Name = "Egg",
                            Status = 1,
                            Unit = 1
                        });
                });

            modelBuilder.Entity("Models.Concrete.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalCalorie")
                        .HasColumnType("float");

                    b.HasKey("MealID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(6123),
                            MealName = "Breakfast",
                            TotalCalorie = 0.0
                        },
                        new
                        {
                            MealID = 2,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(6125),
                            MealName = "Lunch",
                            TotalCalorie = 0.0
                        },
                        new
                        {
                            MealID = 3,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(6126),
                            MealName = "Dinner",
                            TotalCalorie = 0.0
                        },
                        new
                        {
                            MealID = 4,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(6126),
                            MealName = "Snack",
                            TotalCalorie = 0.0
                        });
                });

            modelBuilder.Entity("Models.Concrete.MealSummary", b =>
                {
                    b.Property<int>("MealSummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealSummaryID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MealSummaryID");

                    b.HasIndex("FoodID");

                    b.HasIndex("MealID");

                    b.HasIndex("UserID");

                    b.ToTable("MealSummaries");
                });

            modelBuilder.Entity("Models.Concrete.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreationDate = new DateTime(2024, 3, 27, 14, 34, 51, 10, DateTimeKind.Local).AddTicks(5566),
                            Email = "admin@admin.com",
                            Password = "Admin123*",
                            Status = 1,
                            UserType = 2
                        });
                });

            modelBuilder.Entity("Models.Concrete.UserDetail", b =>
                {
                    b.Property<int>("UserDetailID")
                        .HasColumnType("int");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserDetailID");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Models.Concrete.Food", b =>
                {
                    b.HasOne("Models.Concrete.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Concrete.Meal", null)
                        .WithMany("Foods")
                        .HasForeignKey("MealID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Concrete.MealSummary", b =>
                {
                    b.HasOne("Models.Concrete.Food", "Food")
                        .WithMany("MealSummary")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Concrete.Meal", "Meal")
                        .WithMany("MealSummary")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Concrete.User", "User")
                        .WithMany("MealSummary")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Concrete.UserDetail", b =>
                {
                    b.HasOne("Models.Concrete.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("Models.Concrete.UserDetail", "UserDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Concrete.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Models.Concrete.Food", b =>
                {
                    b.Navigation("MealSummary");
                });

            modelBuilder.Entity("Models.Concrete.Meal", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("MealSummary");
                });

            modelBuilder.Entity("Models.Concrete.User", b =>
                {
                    b.Navigation("MealSummary");

                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
