// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(SlimBuddyDBContext))]
    partial class SlimBuddyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Fruit",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2178)
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Drink",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2189)
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Snack",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2190)
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Dessert",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2190)
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Vegetable",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2191)
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Dairy",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2192)
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Fish and Seafood",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2193)
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Fast Food",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2193)
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Meat or Poultry",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2194)
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Others",
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2195)
                        });
                });

            modelBuilder.Entity("Models.Concrete.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<double>("Calorie")
                        .HasColumnType("float");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Calorie = 52.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2464),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Apple",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 2,
                            Calorie = 47.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2469),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Orange",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 3,
                            Calorie = 131.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2471),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Banana",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 4,
                            Calorie = 46.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2472),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Plum",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 5,
                            Calorie = 61.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2474),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Kiwi",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 6,
                            Calorie = 30.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2475),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Watermelon",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 7,
                            Calorie = 34.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2476),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Melon",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 8,
                            Calorie = 59.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2478),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Peach",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 9,
                            Calorie = 60.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2479),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Mango",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 10,
                            Calorie = 50.0,
                            CategoryID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2480),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cherry",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 11,
                            Calorie = 0.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2482),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Water",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 12,
                            Calorie = 113.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2483),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Milkshake",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 13,
                            Calorie = 37.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2484),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cola",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 14,
                            Calorie = 48.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2486),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Fanta",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 15,
                            Calorie = 89.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2487),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Hot Chocolate",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 16,
                            Calorie = 53.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2488),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Soda",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 17,
                            Calorie = 1.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2491),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Coffee",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 18,
                            Calorie = 45.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2493),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Orange Juice",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 19,
                            Calorie = 2.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2494),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Tea",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 20,
                            Calorie = 42.0,
                            CategoryID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2496),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Lemonade",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 21,
                            Calorie = 433.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2498),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Wafer",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 22,
                            Calorie = 11.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2502),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Almond",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 23,
                            Calorie = 6.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2504),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Peanut",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 24,
                            Calorie = 488.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2506),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Snickers",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 25,
                            Calorie = 375.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2507),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Popcorn",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 26,
                            Calorie = 536.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2509),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Chips",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 27,
                            Calorie = 502.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2518),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cookies",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 28,
                            Calorie = 20.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2520),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Crackers",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 29,
                            Calorie = 559.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2522),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Sunflower Seed",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 30,
                            Calorie = 318.0,
                            CategoryID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2524),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Marshmallow",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 31,
                            Calorie = 321.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2526),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cheesecake",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 32,
                            Calorie = 174.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2527),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Baklava",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 33,
                            Calorie = 438.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2529),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Doughnut",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 34,
                            Calorie = 321.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2530),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Creme brulee",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 35,
                            Calorie = 49.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2532),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cookie",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 36,
                            Calorie = 466.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2533),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Brownie",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 37,
                            Calorie = 250.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2534),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Ice cream",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 38,
                            Calorie = 290.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2536),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Tiramisu",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 39,
                            Calorie = 271.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2537),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Pavlova",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 40,
                            Calorie = 120.0,
                            CategoryID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2538),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Pudding",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 41,
                            Calorie = 33.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2540),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Broccoli",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 42,
                            Calorie = 15.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2541),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cucumber",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 43,
                            Calorie = 42.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2542),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Celery",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 44,
                            Calorie = 16.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2544),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Courgette",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 45,
                            Calorie = 24.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2546),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Eggplant",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 46,
                            Calorie = 19.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2547),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Tomatoes",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 47,
                            Calorie = 41.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2548),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Carrot",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 48,
                            Calorie = 39.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2550),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Pepper",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 49,
                            Calorie = 47.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2552),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Artichoke",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 50,
                            Calorie = 22.0,
                            CategoryID = 5,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2553),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Mushroom",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 51,
                            Calorie = 59.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2555),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Yogurt",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 52,
                            Calorie = 62.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2557),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Tzatziki",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 53,
                            Calorie = 50.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2558),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Ayran",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 54,
                            Calorie = 402.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2559),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cheddar cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 55,
                            Calorie = 98.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2561),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Cottage cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 56,
                            Calorie = 280.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2562),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Mozzarella cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 57,
                            Calorie = 42.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2563),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 58,
                            Calorie = 68.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2564),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Goat milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 59,
                            Calorie = 32.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2566),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Almond milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 60,
                            Calorie = 54.0,
                            CategoryID = 6,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2570),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Soy milk",
                            Status = 1,
                            Unit = 3
                        },
                        new
                        {
                            FoodID = 61,
                            Calorie = 164.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2572),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Octopus",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 62,
                            Calorie = 124.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2573),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Sea Bass",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 63,
                            Calorie = 264.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2574),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Caviar",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 64,
                            Calorie = 89.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2576),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Lobster",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 65,
                            Calorie = 175.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2577),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Calamary",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 66,
                            Calorie = 159.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2578),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Blue Fish",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 67,
                            Calorie = 90.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2581),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Whiting",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 68,
                            Calorie = 206.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2582),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Salmon",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 69,
                            Calorie = 150.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2583),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Sushi",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 70,
                            Calorie = 262.0,
                            CategoryID = 7,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2585),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Mackerel",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 71,
                            Calorie = 295.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2586),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Burger",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 72,
                            Calorie = 266.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2587),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Pizza",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 73,
                            Calorie = 239.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2589),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Doner",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 74,
                            Calorie = 312.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2590),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "French fries",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 75,
                            Calorie = 164.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2591),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Mac and cheese",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 76,
                            Calorie = 118.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2593),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Lahmacun",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 77,
                            Calorie = 390.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2594),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Tantuni",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 78,
                            Calorie = 284.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2595),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Sandwich",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 79,
                            Calorie = 411.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2597),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Onion rings",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 80,
                            Calorie = 203.0,
                            CategoryID = 8,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2598),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Chicken wing",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 81,
                            Calorie = 360.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2599),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Adana Kebab",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 82,
                            Calorie = 235.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2600),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Meatball",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 83,
                            Calorie = 336.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2602),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Salami",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 84,
                            Calorie = 300.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2603),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Sausage",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 85,
                            Calorie = 186.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2604),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Beef Stew",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 86,
                            Calorie = 290.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2606),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Chicken Marsal",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 87,
                            Calorie = 350.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2608),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Chicken Tikka Masala",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 88,
                            Calorie = 308.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2609),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Chimichanga",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 89,
                            Calorie = 290.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2610),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Fajita",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 90,
                            Calorie = 220.0,
                            CategoryID = 9,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2612),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Steak",
                            Status = 1,
                            Unit = 1
                        },
                        new
                        {
                            FoodID = 91,
                            Calorie = 264.0,
                            CategoryID = 10,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2613),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Bread",
                            Status = 1,
                            Unit = 2
                        },
                        new
                        {
                            FoodID = 92,
                            Calorie = 220.0,
                            CategoryID = 10,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2614),
                            Image = "\\FoodPhotos\\2.jpg",
                            Name = "Egg",
                            Status = 1,
                            Unit = 1
                        });
                });

            modelBuilder.Entity("Models.Concrete.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalCalorie")
                        .HasColumnType("float");

                    b.HasKey("MealID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealID = 1,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2854),
                            MealName = "Breakfast",
                            TotalCalorie = 0.0
                        },
                        new
                        {
                            MealID = 2,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2856),
                            MealName = "Lunch",
                            TotalCalorie = 0.0
                        },
                        new
                        {
                            MealID = 3,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2857),
                            MealName = "Dinner",
                            TotalCalorie = 0.0
                        },
                        new
                        {
                            MealID = 4,
                            CreationDate = new DateTime(2024, 3, 22, 18, 15, 31, 255, DateTimeKind.Local).AddTicks(2858),
                            MealName = "Snack",
                            TotalCalorie = 0.0
                        });
                });

            modelBuilder.Entity("Models.Concrete.MealSummary", b =>
                {
                    b.Property<int>("MealSummaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealSummaryID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MealSummaryID");

                    b.HasIndex("FoodID");

                    b.HasIndex("MealID");

                    b.HasIndex("UserID");

                    b.ToTable("MealSummaries");
                });

            modelBuilder.Entity("Models.Concrete.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Concrete.UserDetail", b =>
                {
                    b.Property<int>("UserDetailID")
                        .HasColumnType("int");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserDetailID");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Models.Concrete.Food", b =>
                {
                    b.HasOne("Models.Concrete.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Concrete.MealSummary", b =>
                {
                    b.HasOne("Models.Concrete.Food", "Food")
                        .WithMany("MealSummary")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Concrete.Meal", "Meal")
                        .WithMany("MealSummary")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Concrete.User", "User")
                        .WithMany("MealSummary")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Concrete.UserDetail", b =>
                {
                    b.HasOne("Models.Concrete.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("Models.Concrete.UserDetail", "UserDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Concrete.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Models.Concrete.Food", b =>
                {
                    b.Navigation("MealSummary");
                });

            modelBuilder.Entity("Models.Concrete.Meal", b =>
                {
                    b.Navigation("MealSummary");
                });

            modelBuilder.Entity("Models.Concrete.User", b =>
                {
                    b.Navigation("MealSummary");

                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
